const mongoose = require("mongoose");
const Plato = require("./models/Plato");

const platosParaSubir = [
  { "nombre": "Bowl de Quinoa y Pollo", "calorias": 350, "ingredientes": ["Quinoa", "Pollo"], "categoria": "Almuerzo" },
  { "nombre": "Salmón al Limón", "calorias": 420, "ingredientes": ["Salmón", "Espárragos"], "categoria": "Cena" },
  { "nombre": "Omelette de Claras", "calorias": 200, "ingredientes": ["Huevo", "Champiñones"], "categoria": "Desayuno" },
  { "nombre": "Ensalada César Saludable", "calorias": 310, "ingredientes": ["Lechuga", "Pollo"], "categoria": "Almuerzo" },
  { "nombre": "Tacos de Lechuga con Pavo", "calorias": 280, "ingredientes": ["Lechuga", "Pavo"], "categoria": "Cena" },
  { "nombre": "Smoothie de Berries", "calorias": 180, "ingredientes": ["Arándanos", "Leche"], "categoria": "Desayuno" },
  { "nombre": "Garbanzos Salteados", "calorias": 390, "ingredientes": ["Garbanzos", "Cebolla"], "categoria": "Almuerzo" },
  { "nombre": "Pescado al Vapor", "calorias": 250, "ingredientes": ["Merluza", "Brócoli"], "categoria": "Cena" },
  { "nombre": "Avena con Canela", "calorias": 220, "ingredientes": ["Avena", "Canela"], "categoria": "Desayuno" },
  { "nombre": "Pasta Integral con Brócoli", "calorias": 400, "ingredientes": ["Pasta", "Brócoli"], "categoria": "Almuerzo" },
  { "nombre": "Pechuga a la Plancha", "calorias": 300, "ingredientes": ["Pollo", "Zanahoria"], "categoria": "Cena" },
  { "nombre": "Pudding de Chía", "calorias": 190, "ingredientes": ["Chía", "Coco"], "categoria": "Desayuno" },
  { "nombre": "Lentejas Guisadas", "calorias": 380, "ingredientes": ["Lentejas", "Papa"], "categoria": "Almuerzo" },
  { "nombre": "Tofu Salteado", "calorias": 270, "ingredientes": ["Tofu", "Soya"], "categoria": "Cena" },
  { "nombre": "Tostadas con Aguacate", "calorias": 240, "ingredientes": ["Pan", "Aguacate"], "categoria": "Desayuno" },
  { "nombre": "Arroz Integral con Atún", "calorias": 360, "ingredientes": ["Arroz", "Atún"], "categoria": "Almuerzo" },
  { "nombre": "Sopa de Verduras", "calorias": 150, "ingredientes": ["Zanahoria", "Apio"], "categoria": "Cena" },
  { "nombre": "Yogur Griego con Nueces", "calorias": 210, "ingredientes": ["Yogur", "Nueces"], "categoria": "Desayuno" },
  { "nombre": "Ceviche de Pescado", "calorias": 230, "ingredientes": ["Pescado", "Limón"], "categoria": "Almuerzo" },
  { "nombre": "Brochetas de Pollo", "calorias": 290, "ingredientes": ["Pollo", "Cebolla"], "categoria": "Cena" },
  { "nombre": "Batido de Proteína", "calorias": 200, "ingredientes": ["Proteína"], "categoria": "Snack" },
  { "nombre": "Quiche de Espinacas", "calorias": 320, "ingredientes": ["Huevo", "Espinaca"], "categoria": "Almuerzo" },
  { "nombre": "Crema de Calabacín", "calorias": 140, "ingredientes": ["Calabacín"], "categoria": "Cena" },
  { "nombre": "Fruta Picada", "calorias": 120, "ingredientes": ["Papaya", "Melón"], "categoria": "Desayuno" },
  { "nombre": "Ensalada de Lentejas", "calorias": 340, "ingredientes": ["Lentejas", "Tomate"], "categoria": "Almuerzo" },
  { "nombre": "Pavo con Judías Verdes", "calorias": 260, "ingredientes": ["Pavo", "Judías"], "categoria": "Cena" },
  { "nombre": "Huevos Revueltos", "calorias": 180, "ingredientes": ["Huevo"], "categoria": "Desayuno" },
  { "nombre": "Hummus con Zanahoria", "calorias": 190, "ingredientes": ["Garbanzos", "Zanahoria"], "categoria": "Snack" },
  { "nombre": "Fajitas de Res Magra", "calorias": 410, "ingredientes": ["Res", "Pimiento"], "categoria": "Almuerzo" },
  { "nombre": "Caldo de Pollo", "calorias": 170, "ingredientes": ["Pollo"], "categoria": "Cena" },
  { "nombre": "Panqueques de Avena", "calorias": 250, "ingredientes": ["Avena", "Huevo"], "categoria": "Desayuno" },
  { "nombre": "Ensalada de Pasta Fría", "calorias": 370, "ingredientes": ["Pasta", "Atún"], "categoria": "Almuerzo" },
  { "nombre": "Berenjenas Rellenas", "calorias": 280, "ingredientes": ["Berenjena", "Carne"], "categoria": "Cena" },
  { "nombre": "Queso Fresco con Miel", "calorias": 160, "ingredientes": ["Queso", "Miel"], "categoria": "Snack" },
  { "nombre": "Arroz con Pollo Fit", "calorias": 390, "ingredientes": ["Arroz", "Pollo"], "categoria": "Almuerzo" },
  { "nombre": "Puré de Camote", "calorias": 220, "ingredientes": ["Camote"], "categoria": "Cena" },
  { "nombre": "Bagel Integral", "calorias": 270, "ingredientes": ["Pan", "Queso"], "categoria": "Desayuno" },
  { "nombre": "Gazpacho", "calorias": 130, "ingredientes": ["Tomate", "Pepino"], "categoria": "Almuerzo" },
  { "nombre": "Tataki de Atún", "calorias": 310, "ingredientes": ["Atún", "Sésamo"], "categoria": "Cena" },
  { "nombre": "Manzana con Maní", "calorias": 200, "ingredientes": ["Manzana", "Maní"], "categoria": "Snack" },
  { "nombre": "Risotto de Setas", "calorias": 430, "ingredientes": ["Arroz", "Setas"], "categoria": "Almuerzo" },
  { "nombre": "Tortilla de Patatas Fit", "calorias": 260, "ingredientes": ["Huevo", "Patata"], "categoria": "Cena" },
  { "nombre": "Muesli con Leche", "calorias": 280, "ingredientes": ["Muesli", "Leche"], "categoria": "Desayuno" },
  { "nombre": "Burrito Saludable", "calorias": 450, "ingredientes": ["Tortilla", "Frijoles"], "categoria": "Almuerzo" },
  { "nombre": "Espaguetis de Calabacín", "calorias": 180, "ingredientes": ["Calabacín"], "categoria": "Cena" },
  { "nombre": "Kiwi y Nueces", "calorias": 140, "ingredientes": ["Kiwi", "Nueces"], "categoria": "Snack" },
  { "nombre": "Paella de Marisco", "calorias": 480, "ingredientes": ["Arroz", "Gambas"], "categoria": "Almuerzo" },
  { "nombre": "Wrap de Salmón", "calorias": 330, "ingredientes": ["Tortilla", "Salmón"], "categoria": "Cena" },
  { "nombre": "Galletas de Avena", "calorias": 190, "ingredientes": ["Avena", "Plátano"], "categoria": "Snack" },
  { "nombre": "Estofado de Ternera", "calorias": 460, "ingredientes": ["Ternera"], "categoria": "Almuerzo" },
  { "nombre": "Pizza de Coliflor", "calorias": 350, "ingredientes": ["Coliflor", "Queso"], "categoria": "Cena" },
  { "nombre": "Huevos Benedictinos Fit", "calorias": 380, "ingredientes": ["Huevo", "Pan"], "categoria": "Desayuno" },
  { "nombre": "Poke Bowl", "calorias": 410, "ingredientes": ["Pescado", "Arroz"], "categoria": "Almuerzo" },
  { "nombre": "Minestrone", "calorias": 240, "ingredientes": ["Verduras"], "categoria": "Cena" },
  { "nombre": "Batido de Espinaca", "calorias": 160, "ingredientes": ["Espinaca"], "categoria": "Desayuno" },
  { "nombre": "Tabbouleh", "calorias": 210, "ingredientes": ["Bulgur"], "categoria": "Almuerzo" },
  { "nombre": "Pechuga al Curry", "calorias": 340, "ingredientes": ["Pollo", "Curry"], "categoria": "Cena" },
  { "nombre": "Barrita de Granola", "calorias": 170, "ingredientes": ["Granola"], "categoria": "Snack" },
  { "nombre": "Sushi Roll Fit", "calorias": 320, "ingredientes": ["Arroz", "Pescado"], "categoria": "Almuerzo" },
  { "nombre": "Wok de Verduras", "calorias": 230, "ingredientes": ["Pimiento"], "categoria": "Cena" },
  { "nombre": "Gachas de Avena", "calorias": 260, "ingredientes": ["Avena"], "categoria": "Desayuno" },
  { "nombre": "Albóndigas de Pavo", "calorias": 380, "ingredientes": ["Pavo"], "categoria": "Almuerzo" },
  { "nombre": "Trucha a la Navarra", "calorias": 350, "ingredientes": ["Trucha"], "categoria": "Cena" },
  { "nombre": "Piña con Requesón", "calorias": 180, "ingredientes": ["Piña"], "categoria": "Snack" },
  { "nombre": "Lasaña de Berenjena", "calorias": 390, "ingredientes": ["Berenjena"], "categoria": "Almuerzo" },
  { "nombre": "Hamburguesa de Lentejas", "calorias": 310, "ingredientes": ["Lentejas"], "categoria": "Cena" },
  { "nombre": "Tostada con Huevo", "calorias": 230, "ingredientes": ["Huevo"], "categoria": "Desayuno" },
  { "nombre": "Cuscús Real", "calorias": 420, "ingredientes": ["Cuscús", "Pollo"], "categoria": "Almuerzo" },
  { "nombre": "Salmorejo", "calorias": 190, "ingredientes": ["Tomate"], "categoria": "Cena" },
  { "nombre": "Almendras Tostadas", "calorias": 160, "ingredientes": ["Almendras"], "categoria": "Snack" },
  { "nombre": "Bacalao con Tomate", "calorias": 330, "ingredientes": ["Bacalao"], "categoria": "Almuerzo" },
  { "nombre": "Rollitos Primavera Fit", "calorias": 210, "ingredientes": ["Verduras"], "categoria": "Cena" },
  { "nombre": "Macedonia de Frutas", "calorias": 130, "ingredientes": ["Frutas"], "categoria": "Desayuno" },
  { "nombre": "Pollo Teriyaki", "calorias": 370, "ingredientes": ["Pollo"], "categoria": "Almuerzo" },
  { "nombre": "Champiñones al Ajillo", "calorias": 140, "ingredientes": ["Champiñones"], "categoria": "Cena" },
  { "nombre": "Edamame", "calorias": 120, "ingredientes": ["Soja"], "categoria": "Snack" },
  { "nombre": "Sándwich Veggie", "calorias": 290, "ingredientes": ["Pan", "Hummus"], "categoria": "Almuerzo" },
  { "nombre": "Pisto Manchego", "calorias": 220, "ingredientes": ["Tomate"], "categoria": "Cena" },
  { "nombre": "Tortitas de Arroz", "calorias": 110, "ingredientes": ["Arroz"], "categoria": "Snack" },
  { "nombre": "Codillo de Cerdo Magro", "calorias": 470, "ingredientes": ["Cerdo"], "categoria": "Almuerzo" },
  { "nombre": "Espárragos con Huevo", "calorias": 190, "ingredientes": ["Huevo"], "categoria": "Cena" },
  { "nombre": "Kéfir con Semillas", "calorias": 170, "ingredientes": ["Kéfir"], "categoria": "Desayuno" },
  { "nombre": "Fettuccine Alfredo Fit", "calorias": 430, "ingredientes": ["Pasta"], "categoria": "Almuerzo" },
  { "nombre": "Goulash de Ternera", "calorias": 450, "ingredientes": ["Ternera"], "categoria": "Cena" },
  { "nombre": "Dátiles con Nueces", "calorias": 150, "ingredientes": ["Dátiles"], "categoria": "Snack" },
  { "nombre": "Arroz Tres Delicias Fit", "calorias": 360, "ingredientes": ["Arroz"], "categoria": "Almuerzo" },
  { "nombre": "Revuelto de Ajetes", "calorias": 180, "ingredientes": ["Huevo"], "categoria": "Cena" },
  { "nombre": "Plátano con Avena", "calorias": 240, "ingredientes": ["Plátano"], "categoria": "Desayuno" },
  { "nombre": "Conejo al Horno", "calorias": 310, "ingredientes": ["Conejo"], "categoria": "Almuerzo" },
  { "nombre": "Papillote de Verduras", "calorias": 160, "ingredientes": ["Verduras"], "categoria": "Cena" },
  { "nombre": "Pistachos", "calorias": 170, "ingredientes": ["Pistachos"], "categoria": "Snack" },
  { "nombre": "Solomillo de Pavo", "calorias": 320, "ingredientes": ["Pavo"], "categoria": "Almuerzo" },
  { "nombre": "Ensalada Rusa Fit", "calorias": 280, "ingredientes": ["Patata"], "categoria": "Cena" },
  { "nombre": "Infusión con Galleta", "calorias": 120, "ingredientes": ["Galleta"], "categoria": "Desayuno" },
  { "nombre": "Pulpo a la Gallega", "calorias": 270, "ingredientes": ["Pulpo"], "categoria": "Almuerzo" },
  { "nombre": "Crema de Calabaza", "calorias": 150, "ingredientes": ["Calabaza"], "categoria": "Cena" },
  { "nombre": "Chips de Manzana", "calorias": 100, "ingredientes": ["Manzana"], "categoria": "Snack" },
  { "nombre": "Pasta con Atún", "calorias": 410, "ingredientes": ["Pasta"], "categoria": "Almuerzo" },
  { "nombre": "Tortilla de Espinacas", "calorias": 220, "ingredientes": ["Espinaca"], "categoria": "Cena" },
  { "nombre": "Naranja con Canela", "calorias": 90, "ingredientes": ["Naranja"], "categoria": "Desayuno" }
];

mongoose.connect("mongodb://127.0.0.1:27017/nutriDB")
.then(async () => {
    console.log("Conectado para carga masiva...");
    await Plato.deleteMany({}); // Limpia para no tener datos viejos
    await Plato.insertMany(platosParaSubir);
    console.log("¡Los 100 platos (con Cena) se cargaron con éxito! ✅");
    process.exit();
}).catch(err => console.log(err));